name: wuchuheng_ui
description: wuchuheng ui
version: 1.0.0
homepage: https://github.com/wuchuheng/ui_dart

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
